service: aws-python-flask-book-api

custom:
  stage: ${opt:stage, self:provider.stage}
  wsgi:
    app: main.app

provider:
  name: aws
  runtime: python3.9
  lambdaHashingVersion: "20201221"

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
          cors:
            origins:
              - "*"
      - http:
          path: /{proxy+}
          method: ANY
          cors:
            origins:
              - "*"

plugins:
  - serverless-wsgi
  - serverless-python-requirements
