name: Python application QA

on:
  push:
    branches: ["qa"]

jobs:
  deploy-QA:
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r lab-05/requirements.txt
          pip install flake8 pytest

      - name: Test with pytest
        run: |
          cd lab-05
          pytest tests.py

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Serverless Framework
        run: npm install -g serverless@3

      - name: Deploy to AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        run: |
          cd lab-05

          serverless plugin install --name serverless-wsgi
          serverless plugin install --name serverless-python-requirements
          serverless deploy --stage qa
